# Generated by Django 4.2.5 on 2023-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_carouselitem_link_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(editable=False, null=True),
        ),
    ]
